# -*- coding: utf-8 -*-
"""LAB4_DHT11.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/jumbokh/micropython_class/blob/master/ESP32/LAB4_DHT11.ipynb
"""

'''
材料清單：
DHT11 * 1
10k歐姆電阻 * 1
104 (0.1u)電容 * 1
杜邦線 * 3
data port: D1 (GPIO5)
'''

"""![DHT11](https://github.com/jumbokh/micropython_class/blob/master/ESP32/images/DHT11.jpg?raw=1)
![接線圖](https://github.com/jumbokh/micropython_class/blob/master/ESP32/images/MP_DHT11_bb.jpg?raw=1)
"""

# Commented out IPython magic to ensure Python compatibility.
# %serialconnect --port COM9

from machine import Pin
import dht
import time

d = dht.DHT11(Pin(5))

while True:
    d.measure()
    temp = d.temperature()
    hum = d.humidity()
    print('Humidity: {}%'.format(hum))
    print('Temperature: {}{}C'.format(temp, '\u00b0'))
    time.sleep(5)

